# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'DoctorFei_iOS' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MagicalRecord'
pod 'MBProgressHUD'
pod 'JSMessagesViewController'
pod 'IHKeyboardAvoiding'
pod 'DZNEmptyDataSet'


end

target 'DoctorFei_iOSTests' do

end

