# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'DoctorFei_Patient_iOS' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MagicalRecord'
pod 'MBProgressHUD'
pod 'JSQMessagesViewController'
pod 'IHKeyboardAvoiding'
pod 'DZNEmptyDataSet'
pod 'ReactiveCocoa'
pod 'JSONKit-NoWarning'
pod 'CocoaAsyncSocket'
pod 'JSBadgeView'
pod 'DateTools'
pod 'Reachability'
pod 'UMengAnalytics-NO-IDFA'
pod 'RHAddressBook'
pod 'WYPopoverController'
pod 'THContactPicker', :git => 'https://github.com/MiracleJ/THContactPicker'
pod 'ActionSheetPicker-3.0'
pod 'Masonry'
end

